### PR TITLE
Implement task name autocompletion

### PR DESCRIPTION
**Pull request by jlledom**
Hi, I wrote some changes to implement task autocompletion through a GTK input drop down. If accepted, this PR would close https://github.com/lakoliu/Furtherance/issues/103

There's a glitch in the drop down I don't know how to fix: when the query returns only one result, a empty whitespace is shown in the dropdown:

imatge

I noticed some other strange behaviors, like:

- When the dropdown is open and I switch to another window, the dropdown keeps visible on top of other windows.
- Mouse selection inside the dropdown not always works.

I think these are probably bugs in GTK itself, as `gtk::EntryCompletion` is marked as deprecated. But I couldn't find any other component in GTK 4 which implements such functionality.

I took this task as an exercise to learn rust and GTK, so it could have made some beginner mistakes. Please review it with care, fortunately, it's not much code.

### CODE REVIEW

**Comment by lakoliu** [comment]
This sounds awesome, thank you for doing this! I'm moving this weekend so I won't be able to look at it for the next few days, but I'll take a look as soon as possible.

**Comment by lakoliu** [comment]
Thank you for your patience and thank you very much for implementing this! It looks really good! It's too bad that EntryCompletion is deprecated so we will need to alter this code when GTK 5 comes out, but oh well.

**Comment by jlledom** [comment]
Thanks for merging. Are you OK with those glitches I mentioned?

**Comment by lakoliu** [comment]
I'm actually not seeing either of those problems (Fedora 38). I will probably make this an option in the Preferences anyway, so if users do see these bugs and are annoyed by them they can turn off autocomplete.

**Comment by jlledom** [comment]
> I'm actually not seeing either of those problems (Fedora 38).

I'm using Debian stable. Glad to know it works fine in more modern systems.

> I will probably make this an option in the Preferences anyway, so if users do see these bugs and are annoyed by them they can turn off autocomplete.

Nice.

**Comment by lakoliu** [comment]
I did find another bug though - if the auto-complete drop down appears and you don't do anything with it and just click the start button, the drop down stays there until you stop the timer. I will try to find a way around that.

**Comment by jlledom** [comment]
> I did find another bug though - if the auto-complete drop down appears and you don't do anything with it and just click the start button, the drop down stays there until you stop the timer. I will try to find a way around that.

I could reproduce this locally. I think this is a bug in GTK: the widget should be responsible of hiding the popup when losing the focus, and not expect the user to do it manually.

I've spent some time trying to add a listener for the focus-out/blur event on the input, to manually hide the popup on that event, but I found that:

1. The focus-out event doesn't seem to exist in GTK4.
2. GTK doesn't provide a method to hide the popup anyway 🙃.

I hope you find a workaround for this. I could check it myself but I'll need some weeks before I can focus on Furtherance again.

**Comment by lakoliu** [comment]
I was able to fix that bug by just disabling autocompletion when a task is started and enabling it again when it is stopped. I also added a preference to turn it on and off, and fixed a bug where it was showing an empty "#" if there weren't any tags on a task name. Thanks again for this, it's working great!

**Pull request merged**
