### PR TITLE
feat: add csv export

### PR DESCRIPTION
**Pull request by flxzt**
Hey! I thought CSV export would be nice, so here it is with some basic options:
- sort by task name, start time, stop time
- in ascending or descending order

This could also be a starter to add custom sort the report with those options.

Thanks for the app and let me know what you think!

### CODE REVIEW

**Comment by flxzt** [comment]
just noticed the codebase not formatted with rust fmt, sorry about the fmt noise in the PR. (although I think it might be worth considering always formatting in the future to avoid this )

**Comment by lakoliu** [comment]
This looks really good, thank you for doing all of that! I definitely need to clean up the formatting. I created Furtherance as a way to learn Rust so a lot of the code is a bit messy.

**Comment by flxzt** [comment]
I didn't use it myself yet, but the [rust-gtk-template](https://gitlab.gnome.org/World/Rust/gtk-rust-template/-/blob/master/hooks/pre-commit.hook) features a pre-commit hook executing `rust fmt`, that might be useful. :)

**Comment by lakoliu** [comment]
Do you know how we can localize the "nick" strings used in the enums you created for TaskSort and SortOrder? I'm not sure how to localize strings in an enum (Issue #68). Thanks!

**Comment by flxzt** [comment]
hmm, I don't know actually :/. Maybe this needs to be refactored into a string list to display the enum options in the UI, and then match on the index of the current selected string

**Pull request merged**
